/* ThermoBase v10 — scientific exploration layer
   The v9 visual language is retained; this layer makes the underlying research explorable.
*/
let D=null,currentML='random',currentWorld='enceladus',activeEnv=null,activePathway=null;
const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
const plotCfg={responsive:true,displaylogo:false,scrollZoom:true};
const baseLayout={paper_bgcolor:'transparent',plot_bgcolor:'transparent',font:{family:'Inter, sans-serif',color:'#656a61',size:10},margin:{l:58,r:24,t:48,b:50},autosize:true,hoverlabel:{font:{size:11}},legend:{font:{size:10}}};
const num=v=>v==null||v===''||v==='NA'||v==='null'?null:Number(v);
const fmt=(v,d=2)=>v==null||Number.isNaN(Number(v))?'—':Number(v).toLocaleString(undefined,{maximumFractionDigits:d});
const esc=s=>String(s??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));
function vals(a,k){return a.map(r=>num(r[k])).filter(v=>v!=null)}
function median(a){a=a.filter(v=>v!=null).sort((x,y)=>x-y);return a.length?a[Math.floor(a.length/2)]:null}
function quant(a,q){a=a.filter(v=>v!=null).sort((x,y)=>x-y);if(!a.length)return null;return a[Math.min(a.length-1,Math.max(0,Math.round((a.length-1)*q)))]}
function countBy(a,key){const c={};a.forEach(r=>{const k=typeof key==='function'?key(r):r[key];if(k!=null&&String(k).trim())c[k]=(c[k]||0)+1});return c}
function tokens(v){return String(v||'').split(/[,;|]/).map(s=>s.trim()).filter(Boolean)}
function pathwaysOf(r){return tokens(r.metabolism_pathways)}
function hasPath(r,p){return String(r.metabolism_pathways||'').toLowerCase().includes(String(p).toLowerCase())}
function compoundsOf(r){return tokens(r.extracted_compounds)}
function plot(id,data,layout={}){const el=document.getElementById(id);if(!el||!window.Plotly)return;try{Plotly.purge(el);Plotly.newPlot(el,data,{...baseLayout,...layout,autosize:true},plotCfg).then(()=>Plotly.Plots.resize(el));}catch(e){console.error('Plot failed',id,e)}}
function setText(id,html){const e=$(id);if(e)e.innerHTML=html}
function cardInsight(label,title,text){return `<div class="deep-read"><span>${esc(label)}</span><b>${esc(title)}</b><p>${text}</p></div>`}
function filtered(){if(!D)return[];const dom=$('#fDomain')?.value||'',env=$('#fEnvironment')?.value||'',t=num($('#fTopt')?.value),ph=num($('#fPh')?.value),met=$('#fMet')?.value||'';return D.records.filter(r=>(!dom||r.domain===dom)&&(!env||r.environment===env)&&(t==null||num(r.avg_optimum_temp_c)>=t)&&(ph==null||num(r.avg_optimum_ph)<=ph)&&(!met||hasPath(r,met)))}
function pathwayCounts(a=D.records){const c={};a.forEach(r=>pathwaysOf(r).forEach(x=>c[x]=(c[x]||0)+1));return c}
function go(id){if(!$('#'+id))id='overview';$$('.view').forEach(v=>v.classList.remove('active'));$('#'+id).classList.add('active');$$('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===id));history.replaceState(null,'','#'+id);window.scrollTo({top:0,left:0,behavior:'instant'});renderView(id);updateChatContext()}
function populateFilters(){const e=$('#fEnvironment'),m=$('#fMet');if(e){Object.keys(D.environment_top).sort().forEach(x=>e.insertAdjacentHTML('beforeend',`<option value="${esc(x)}">${esc(x)}</option>`))}if(m){Object.entries(pathwayCounts()).sort((a,b)=>b[1]-a[1]).forEach(([x,n])=>m.insertAdjacentHTML('beforeend',`<option value="${esc(x)}">${esc(x)} (${n})</option>`))}}
function toggleTheme(){const dark=document.documentElement.dataset.theme==='dark';document.documentElement.dataset.theme=dark?'':'dark';localStorage.setItem('tb-theme',dark?'light':'dark');$('#themeToggle').textContent=dark?'Dark mode':'Light mode';setTimeout(()=>renderView($('.view.active')?.id||'overview'),60)}
function init(){
 $('#dataStatus').textContent=`validated research layer · ${D.meta.records.toLocaleString()} records · ${D.meta.columns} fields`;
 populateFilters();
 const saved=localStorage.getItem('tb-theme');if(saved==='dark'){document.documentElement.dataset.theme='dark';$('#themeToggle').textContent='Light mode'}
 bind();renderView(location.hash.slice(1)||'overview');updateChatContext();
}
function renderView(v){({overview:renderOverview,physiology:renderPhys,environment:renderEnvironment,metabolism:renderMetabolism,evidence:renderEvidence,analysis:renderAnalysis,ml:renderML,worlds:()=>renderWorld(currentWorld),synthesis:renderSynthesis})[v]?.()}

function renderOverview(){
 const d=Object.entries(D.domain_counts);plot('overviewDomain',[{x:d.map(x=>x[0]),y:d.map(x=>x[1]),type:'bar',text:d.map(x=>x[1]),textposition:'outside',hovertemplate:'%{x}<br>%{y} records<extra></extra>'}],{yaxis:{title:'Records'},title:{text:'Domain composition',font:{size:13}}});
 const e=Object.entries(D.ecosystem_top).slice(0,10).reverse();plot('overviewEco',[{x:e.map(x=>x[1]),y:e.map(x=>x[0]),type:'bar',orientation:'h',hovertemplate:'%{y}: %{x} records<extra></extra>'}],{margin:{l:160,r:15,t:35,b:40},xaxis:{title:'Records'},title:{text:'Most represented ecosystems',font:{size:13}}});
 const m=Object.entries(D.missing_counts).sort((a,b)=>a[1]-b[1]);plot('overviewMissing',[{x:m.map(x=>x[0].replaceAll('_',' ')),y:m.map(x=>x[1]),type:'bar',hovertemplate:'%{x}<br>%{y} missing<extra></extra>'}],{xaxis:{tickangle:-35,automargin:true},yaxis:{title:'Missing records'},title:{text:'Coverage is uneven across dimensions',font:{size:13}},margin:{l:50,r:15,t:45,b:90}});
 const groups=Object.entries(D.schema_groups);plot('dataArchitecture',[{labels:groups.map(x=>x[0]),parents:groups.map(()=>''),values:groups.map(x=>x[1]),type:'treemap',branchvalues:'total',hovertemplate:'%{label}<br>%{value} fields<extra></extra>'}],{margin:{l:5,r:5,t:42,b:5},title:{text:'How 337 fields are organized',font:{size:13}}});
 setText('overviewDeep',cardInsight('READ THE ARCHITECTURE','The dataset is wider than the headline variables suggest.',`The release contains <strong>${D.meta.columns}</strong> structured fields. ${Object.entries(D.schema_groups).map(([k,v])=>`${esc(k)} (${v})`).join(' · ')}. The analytical story therefore cannot be reconstructed from temperature and pH alone: chemistry, provenance, pressure, salinity and ML-derived fields are part of the research object.`)+cardInsight('FIRST LIMITATION','Missingness is structured, not random.',`Temperature is comparatively complete, while pH and pressure are sparse. That asymmetry determines which questions can be answered directly and which require a measured-subset interpretation.`));
}

function renderPhys(){
 const a=filtered(),T=vals(a,'avg_optimum_temp_c'),P=vals(a,'avg_optimum_ph');
 setText('physKpis',[['Records',a.length],['Topt median',fmt(median(T),1)+' °C'],['pHopt median',fmt(median(P),1)],['Thermal complete',a.filter(r=>num(r.min_temp_c)!=null&&num(r.avg_optimum_temp_c)!=null&&num(r.max_temp_c)!=null).length]].map(x=>`<div><b>${x[1]}</b><span>${x[0]}</span></div>`).join(''));
 const pts=a.filter(r=>num(r.avg_optimum_temp_c)!=null&&num(r.avg_optimum_ph)!=null);const size=pts.map(r=>Math.max(6,Math.min(22,(num(r.avg_opt_salinity_percent_normalized_v40)||0)*1.5+6)));
 plot('physScatter',[{x:pts.map(r=>num(r.avg_optimum_temp_c)),y:pts.map(r=>num(r.avg_optimum_ph)),mode:'markers',type:'scattergl',marker:{size,opacity:.72},text:pts.map(r=>r.name),customdata:pts.map(r=>[r.domain,r.phylum,r.environment,r.metabolism_pathways||'—',r.optimum_pressure_mpa??'—',r.avg_opt_salinity_percent_normalized_v40??'—',r.record_id]),hovertemplate:'<b>%{text}</b><br>Topt %{x} °C · pHopt %{y}<br>%{customdata[0]} · %{customdata[1]}<br>%{customdata[2]}<br>Pathways: %{customdata[3]}<br>Pressure: %{customdata[4]} MPa · salinity: %{customdata[5]}%<extra>Record %{customdata[6]}</extra>'}],{xaxis:{title:'Optimum temperature (°C)'},yaxis:{title:'Optimum pH'},title:{text:`${pts.length.toLocaleString()} records occupy the measured Topt × pHopt plane`,font:{size:13}},dragmode:'select'});
 const bins=[['≤40',0],['40–60',0],['60–80',0],['80–100',0],['>100',0]];T.forEach(x=>bins[x<=40?0:x<=60?1:x<=80?2:x<=100?3:4][1]++);plot('physThermal',[{x:bins.map(x=>x[0]),y:bins.map(x=>x[1]),type:'bar',hovertemplate:'%{x}: %{y}<extra></extra>'}],{title:{text:'Optimum temperature distribution',font:{size:13}},yaxis:{title:'Records'}});
 setText('thermalSummary',`Median Topt <b>${fmt(median(T),1)} °C</b> · ≥80°C <b>${T.filter(x=>x>=80).length}</b> · >100°C <b>${T.filter(x=>x>100).length}</b>`);
 const par=pts.slice(0,850);plot('parallelPhys',[{type:'parcoords',line:{color:par.map(r=>num(r.avg_optimum_temp_c)||0),colorscale:'Viridis',showscale:true,colorbar:{title:'Topt'}},dimensions:[{label:'Topt °C',values:par.map(r=>num(r.avg_optimum_temp_c))},{label:'pHopt',values:par.map(r=>num(r.avg_optimum_ph))},{label:'Salinity %',values:par.map(r=>num(r.avg_opt_salinity_percent_normalized_v40))},{label:'Pressure MPa',values:par.map(r=>num(r.optimum_pressure_mpa))}]}],{title:{text:'Multidimensional physiological trajectories · up to 850 measured records',font:{size:13}},margin:{l:55,r:40,t:45,b:25}});
 const fields=['min_temp_c','avg_optimum_temp_c','max_temp_c','min_ph','avg_optimum_ph','max_ph','avg_opt_salinity_percent_normalized_v40','optimum_pressure_mpa'];const labels=['Tmin','Topt','Tmax','pHmin','pHopt','pHmax','salinity','pressure'];plot('coverageHeat',[{z:[fields.map(k=>a.filter(r=>num(r[k])!=null).length)],x:fields,y:['available'],type:'heatmap',text:[fields.map(k=>`${a.filter(r=>num(r[k])!=null).length} / ${a.length}`)],texttemplate:'%{text}',hovertemplate:'%{x}<br>%{z} available<extra></extra>'}],{xaxis:{ticktext:labels,tickvals:fields},title:{text:'Measurement coverage in the active filter',font:{size:13}},margin:{l:75,r:20,t:50,b:75}});
 plot('tempCoverage',[{x:['Tmin','Topt','Tmax'],y:['min_temp_c','avg_optimum_temp_c','max_temp_c'].map(k=>a.filter(r=>num(r[k])!=null).length),type:'bar'}],{title:{text:'Thermal measurements',font:{size:12}}});plot('phCoverage',[{x:['pHmin','pHopt','pHmax'],y:['min_ph','avg_optimum_ph','max_ph'].map(k=>a.filter(r=>num(r[k])!=null).length),type:'bar'}],{title:{text:'pH measurements',font:{size:12}}});
 plot('nicheMatrix',[{x:['Temperature','pH','Salinity','Pressure'],y:['Temperature','pH','Salinity','Pressure'],z:[['—',null,null,null],[null,'—',null,null],[null,null,'—',null],[null,null,null,'—']],type:'heatmap',colorscale:'Greys',showscale:false,hoverinfo:'skip'}],{title:{text:'Niche dimensions are coupled — use the scatter and parallel view to interrogate them',font:{size:13}}});
 setText('physList',a.slice(0,30).map(r=>`<button class="record-hit" data-record="${esc(r.record_id)}"><b>${esc(r.name)}</b><span>${esc(r.domain||'—')} · ${esc(r.environment||'—')}</span><small>Topt ${r.avg_optimum_temp_c??'—'} °C · pH ${r.avg_optimum_ph??'—'} · ${esc(r.metabolism_pathways||'—')}</small></button>`).join(''));
 setText('physDeep',cardInsight('HOW TO EXPLORE','Start with the cloud, then ask what survives across dimensions.',`Box-select or zoom the Topt × pH plane. The same records can be followed through the parallel-coordinates view, where pressure and salinity become visible. Use the filters above to turn a global pattern into a question about a specific environmental or metabolic subset.`)+cardInsight('SCIENTIFIC CAUTION','The empty regions are not necessarily biological exclusions.',`The pH and pressure layers are sparse. A region without points can represent true rarity, sampling bias, missing measurement, or unresolved source context. The evidence dashboard later shows exactly how much of each dimension is observed.`));
}

function renderEnvironment(){
 const e=Object.entries(D.environment_top).slice(0,14).reverse();plot('envChart',[{x:e.map(x=>x[1]),y:e.map(x=>x[0]),type:'bar',orientation:'h',customdata:e.map(x=>x[0]),hovertemplate:'%{y}<br>%{x} records<extra>Click to drill down</extra>'}],{margin:{l:170,r:15,t:35,b:40},xaxis:{title:'Records'},title:{text:'Environmental representation',font:{size:13}}});
 const vals=[];Object.entries(D.environment_top).forEach(([k,n])=>{const a=D.records.filter(r=>r.environment===k),t=valsOf(a,'avg_optimum_temp_c');if(t.length)vals.push({k,n,m:median(t),q1:quant(t,.25),q3:quant(t,.75)})});vals.sort((a,b)=>a.m-b.m);plot('envTemp',[{x:vals.map(x=>x.m),y:vals.map(x=>x.k),type:'bar',orientation:'h',error_x:{type:'data',array:vals.map(x=>x.q3-x.m),arrayminus:vals.map(x=>x.m-x.q1)},text:vals.map(x=>`n=${x.n}`),hovertemplate:'%{y}<br>Median Topt %{x:.1f} °C<br>%{text}<extra></extra>'}],{margin:{l:170,r:25,t:35,b:40},xaxis:{title:'Median Topt (°C)'},title:{text:'Thermal regime by environment · median with IQR',font:{size:13}}});
 const envs=Object.keys(D.environment_top).slice(0,12),paths=['methanogenesis','sulfate-reduction','sulfur-reduction','iron-reduction','fermentation','hydrogen-oxidation'];const z=envs.map(en=>paths.map(p=>D.records.filter(r=>r.environment===en&&hasPath(r,p)).length));plot('envMetHeat',[{z,x:paths.map(p=>p.replaceAll('-',' ')),y:envs,type:'heatmap',colorscale:'Viridis',hovertemplate:'%{y}<br>%{x}: %{z} records<extra>Click to filter</extra>'}],{title:{text:'Environment × metabolic pathway',font:{size:13}},margin:{l:160,r:20,t:50,b:85}});
 const oxy=Object.keys(D.oxygen_counts);plot('oxygenTemp',[{x:oxy,y:oxy.map(o=>median(valsOf(D.records.filter(r=>r.oxygen_requirement===o),'avg_optimum_temp_c'))),text:oxy.map(o=>D.oxygen_counts[o]),type:'bar',texttemplate:'n=%{text}',hovertemplate:'%{x}<br>Median Topt %{y:.1f} °C<extra></extra>'}],{yaxis:{title:'Median Topt (°C)'},title:{text:'Oxygen regime × thermal niche',font:{size:13}},xaxis:{automargin:true}});
 const p=Object.entries(D.phylum_top).slice(0,16).reverse();plot('phylumChart',[{x:p.map(x=>x[1]),y:p.map(x=>x[0]),type:'bar',orientation:'h',hovertemplate:'%{y}: %{x} records<extra></extra>'}],{margin:{l:150,r:15,t:35,b:35},title:{text:'Taxonomic structure · top phyla',font:{size:12}}});
 const envTop=Object.entries(D.environment_top);plot('envSunburst',[{type:'sunburst',labels:['All environments',...envTop.map(x=>x[0])],parents:['',...envTop.map(()=> 'All environments')],values:[envTop.reduce((s,x)=>s+x[1],0),...envTop.map(x=>x[1])],branchvalues:'total',hovertemplate:'%{label}<br>%{value} records<extra></extra>'}],{margin:{l:5,r:5,t:30,b:5},title:{text:'Environmental composition',font:{size:13}}});
 $('#envChart').off?.('plotly_click');$('#envChart').on?.('plotly_click',ev=>{const name=ev.points?.[0]?.y;if(name)drillEnvironment(name)});$('#envMetHeat').off?.('plotly_click');$('#envMetHeat').on?.('plotly_click',ev=>{const en=ev.points?.[0]?.y,p=String(ev.points?.[0]?.x||'').replaceAll(' ','-');if(en){activeEnv=en;activePathway=p;drillEnvironment(en,p)}});
 if(!activeEnv)drillEnvironment(Object.keys(D.environment_top)[0]);
 setText('envDeep',cardInsight('DRILL DOWN','Click an environment instead of reading it as a category.',`The selected environment becomes a local research slice: how many records it contains, its thermal/pH profile, dominant pathways, domain mix and representative organisms. This is the bridge from descriptive composition to a testable environmental question.`)+cardInsight('CONFOUNDING','The same environment can be represented by a narrow set of lineages.',`That is why the taxonomic panel is deliberately adjacent to the environmental plots. The ML stage later asks whether environment-only signal survives a phylum-grouped holdout.`));
}
function valsOf(a,k){return vals(a,k)}
function drillEnvironment(en,p){activeEnv=en;activePathway=p||null;const a=D.records.filter(r=>r.environment===en),t=valsOf(a,'avg_optimum_temp_c'),ph=valsOf(a,'avg_optimum_ph'),pc=pathwayCounts(a);const top=Object.entries(pc).sort((x,y)=>y[1]-x[1]).slice(0,5);setText('envDrill',`<b>${esc(en)}</b><div class="drill-grid"><span><b>${a.length}</b> records</span><span><b>${fmt(median(t),1)} °C</b> median Topt</span><span><b>${fmt(median(ph),1)}</b> median pHopt</span><span><b>${top[0]?.[1]??0}</b> top pathway count</span></div><p>${p?`Active pathway: <strong>${esc(p.replaceAll('-',' '))}</strong>. `:''}Click another bar to replace this slice.</p><div class="drill-paths">${top.map(([k,n])=>`<button data-envpath="${esc(k)}">${esc(k)} · ${n}</button>`).join('')}</div>`);}

function renderMetabolism(){
 const a=D.records;const counts=pathwayCounts(a),terms=Object.entries(counts).sort((x,y)=>y[1]-x[1]).slice(0,18);plot('metChart',[{x:terms.map(x=>x[1]),y:terms.map(x=>x[0]),type:'bar',orientation:'h',customdata:terms.map(x=>x[0]),hovertemplate:'%{y}: %{x} records<extra>Click to trace</extra>'}],{margin:{l:180,r:20,t:35,b:35},title:{text:'Metabolic capabilities in the release',font:{size:13}},xaxis:{title:'Records'}});
 const c=Object.entries(D.chemical_role);plot('chemChart',[{x:c.map(x=>x[1]),y:c.map(x=>x[0].replaceAll('_',' ')),type:'bar',orientation:'h',hovertemplate:'%{y}: %{x} records<extra></extra>'}],{title:{text:'Chemical-role disposition',font:{size:13}},margin:{l:245,r:15,t:38,b:35},xaxis:{title:'Records'}});
 const comp={};a.forEach(r=>compoundsOf(r).forEach(x=>comp[x]=(comp[x]||0)+1));const top=Object.entries(comp).sort((x,y)=>y[1]-x[1]).slice(0,28);const edges={};a.forEach(r=>{const ps=pathwaysOf(r).slice(0,3),cs=compoundsOf(r).filter(x=>top.some(t=>t[0]===x)).slice(0,4);ps.forEach(pp=>cs.forEach(cc=>{const k=pp+'|'+cc;edges[k]=(edges[k]||0)+1}))});const es=Object.entries(edges).sort((x,y)=>y[1]-x[1]).slice(0,40);plot('chemNetwork',[{x:es.map(([,v])=>v),y:es.map(([k])=>k.replace('|',' → ')),type:'bar',orientation:'h',hovertemplate:'%{y}<br>%{x} records share this pathway–compound context<extra></extra>'}],{margin:{l:230,r:20,t:35,b:35},title:{text:'Recurring pathway–compound contexts',font:{size:13}},xaxis:{title:'Record co-occurrences'}});
 const left=terms.slice(0,8).map(x=>x[0]),right=top.slice(0,14).map(x=>x[0]),sn=[...left,...right],idx={};sn.forEach((x,i)=>idx[x]=i);const src=[],tar=[],val=[];left.forEach(p=>right.forEach(cmp=>{const v=a.filter(r=>hasPath(r,p)&&compoundsOf(r).includes(cmp)).length;if(v){src.push(idx[p]);tar.push(idx[cmp]);val.push(v)}}));plot('pathChemSankey',[{type:'sankey',orientation:'h',node:{label:sn,pad:16,thickness:15},link:{source:src,target:tar,value:val}}],{margin:{l:5,r:5,t:40,b:5},title:{text:'Metabolic pathway → extracted chemistry',font:{size:13}}});
 plot('chemRoleMatrix',[{z:[['substrate','donor','acceptor','product','context','unresolved'].map(k=>c.find(x=>x[0].toLowerCase().includes(k))?.[1]||0)],x:['substrate','donor','acceptor','product','context','unresolved'],y:['records'],type:'heatmap',colorscale:'Viridis',texttemplate:'%{z}',hovertemplate:'%{x}: %{z} records<extra></extra>'}],{title:{text:'Chemical roles are evidence states, not just labels',font:{size:13}},margin:{l:70,r:15,t:45,b:65}});
 setText('pathwayCards',D.pathways.map(p=>`<article class="pathway ${activePathway&&p.pathway.toLowerCase().includes(activePathway.replaceAll('-',' '))?'selected':''}"><div class="score">${p.score}/14</div><b>${esc(p.pathway)}</b><small>${esc(p.interpretation)}</small><p>${esc(p.why)}</p><span class="reaction">${esc(p.reaction)}</span></article>`).join(''));
 renderMetSearch($('#metSearch')?.value||'');setText('metDeep',cardInsight('FOLLOW A PATHWAY','Clicking a pathway is meant to change the question, not just the color.',`A pathway can be traced into the organisms that carry it, the environments where those records occur, and the compounds that appear in their source context. The chemistry network is intentionally described as <em>contextual co-occurrence</em>, not a mechanistic reaction graph.`)+cardInsight('CHEMICAL CAUTION','A compound mention is not automatically a metabolic role.',`The release retains 170 records with unresolved chemical-role context. This prevents a convenient but scientifically dangerous transformation from “compound mentioned” to “compound used by metabolism.”`));
}
function renderMetSearch(q){const res=$('#metSearchResults');if(!res)return;const term=q.trim().toLowerCase();if(!term){res.innerHTML='<span>Search the full record layer — organism, pathway, compound, environment or predicted biosignature.</span>';return}const hits=D.records.filter(r=>[r.name,r.metabolism_pathways,r.extracted_compounds,r.predicted_biosignature_species,r.environment,r.chemical_role_final_disposition_v72].some(v=>String(v||'').toLowerCase().includes(term))).slice(0,60);res.innerHTML=`<div class="search-head"><b>${hits.length}</b> matching records${hits.length>=60?' · first 60 shown':''}</div>`+(hits.length?`<div class="search-grid">${hits.map(r=>`<button class="record-hit" data-record="${esc(r.record_id)}"><b>${esc(r.name)}</b><span>${esc(r.environment||'—')} · ${esc(r.metabolism_pathways||'—')}</span><small>${esc(r.extracted_compounds||'No extracted compounds')}</small></button>`).join('')}</div>`:'<span>No matching record found in the ThermoBase research layer.</span>')}

function renderEvidence(){
 const m=Object.entries(D.missing_counts).sort((a,b)=>b[1]-a[1]);plot('missingChart',[{x:m.map(x=>x[1]),y:m.map(x=>x[0].replaceAll('_',' ')),type:'bar',orientation:'h',hovertemplate:'%{y}<br>%{x} missing<extra></extra>'}],{margin:{l:185,r:20,t:35,b:35},title:{text:'Missingness by key field',font:{size:13}},xaxis:{title:'Missing records'}});
 const q=Object.entries(D.quality_counts);plot('qualityChart',[{x:q.map(x=>x[1]),y:q.map(x=>x[0]),type:'bar',orientation:'h',hovertemplate:'%{y}: %{x}<extra></extra>'}],{title:{text:'Record-level QC disposition',font:{size:13}},margin:{l:230,r:15,t:38,b:35},xaxis:{title:'Records'}});
 plot('qcConsequence',[{x:['Broad descriptive','Complete thermal','Complete pH','Chemistry high-confidence','Current QC pass'],y:[1238,D.completeness.thermal_complete,D.completeness.ph_complete,264,D.quality_counts.QC_PASS_CURRENT_LAYERS],type:'bar',hovertemplate:'%{x}: %{y}<extra></extra>'}],{title:{text:'Analytical coverage depends on the question',font:{size:13}},yaxis:{title:'Records'}});
 const ql=Object.entries(D.quality_counts);plot('provenanceSankey',[{type:'sankey',node:{label:['1,238 records',...ql.map(x=>x[0])],pad:18,thickness:16},link:{source:ql.map(()=>0),target:ql.map((_,i)=>i+1),value:ql.map(x=>x[1])}}],{title:{text:'Current record-level evidence disposition',font:{size:13}},margin:{l:5,r:5,t:45,b:5}});
 const timeline=[['S1 baseline',1238],['Thermal/pH QC',1137],['Chemical adjudication',264],['Current QC pass',1066]];plot('evidenceTimeline',[{x:timeline.map(x=>x[0]),y:timeline.map(x=>x[1]),type:'scatter',mode:'lines+markers',line:{shape:'spline'},hovertemplate:'%{x}<br>%{y} records<extra></extra>'}],{title:{text:'How the evidence layer narrows usable claims',font:{size:13}},yaxis:{title:'Records retained at layer'}});
 const impact=[['Temperature',D.thermal.Topt.n],['pH',D.ph.pHopt.n],['Pressure',D.meta.records-D.missing_counts.optimum_pressure_mpa],['Salinity',D.meta.records-D.missing_counts.avg_opt_salinity_pct],['Chemistry roles',264]];plot('fieldImpact',[{x:impact.map(x=>x[0]),y:impact.map(x=>x[1]),type:'bar',text:impact.map(x=>x[1]),textposition:'outside',hovertemplate:'%{x}: %{y} records with usable values<extra></extra>'}],{title:{text:'Usable evidence by scientific layer',font:{size:13}},yaxis:{title:'Records'}});
 renderSchema();setText('evidenceDeep',cardInsight('WHY THIS EXISTS','QC is not a single cleanliness score.',`A record can be suitable for temperature analysis while still being unsuitable for a source-sensitive pressure claim. The app therefore carries exceptions forward instead of deleting them or hiding them behind one “clean” label.`)+cardInsight('PROVENANCE PRINCIPLE','Original S1 and literature augmentation are not interchangeable.',`Corrections and additions remain traceable in the research pipeline. The website presents the integrated release, while the unresolved cases remain visible as explicit limits on interpretation.`));
}
function renderSchema(){const sg=$('#schemaGroup');if(sg&&sg.options.length===1)Object.keys(D.schema_groups).sort().forEach(g=>sg.insertAdjacentHTML('beforeend',`<option value="${esc(g)}">${esc(g)} (${D.schema_groups[g]})</option>`));const q=($('#schemaSearch')?.value||'').toLowerCase(),g=$('#schemaGroup')?.value||'';const all=D.schema_fields.filter(x=>(!g||x.group===g)&&(!q||x.name.toLowerCase().includes(q)));const fields=all.slice(0,337);$('#schemaExplorer').innerHTML=`<div class="schema-count">Showing ${fields.length} of ${D.schema_fields.length} fields${q?' matching “'+esc(q)+'”':''}</div><div class="schema-grid">${fields.map(x=>`<div><span>${esc(x.group)}</span><b>${esc(x.name)}</b></div>`).join('')}</div>`}

function renderAnalysis(){
 const bins=D.thermal_bins;plot('analysisThermal',[{x:bins.map(x=>x.bin),y:bins.map(x=>x.count),type:'bar',hovertemplate:'%{x}: %{y}<extra></extra>'}],{title:{text:'Observed optimum-temperature distribution',font:{size:13}},yaxis:{title:'Records'}});
 const p=D.ph;plot('analysisPh',[{x:['pHmin','pHopt','pHmax'],y:[p.pHmin.median,p.pHopt.median,p.pHmax.median],type:'bar',error_y:{type:'data',symmetric:false,array:[p.pHmin.q75-p.pHmin.median,p.pHopt.q75-p.pHopt.median,p.pHmax.q75-p.pHmax.median],arrayminus:[p.pHmin.median-p.pHmin.q25,p.pHopt.median-p.pHopt.q25,p.pHmax.median-p.pHmax.q25]}}],{title:{text:'pH envelopes · median and IQR',font:{size:13}},yaxis:{title:'pH'}});
 const a=D.records.filter(r=>num(r.avg_optimum_temp_c)!=null&&num(r.avg_optimum_ph)!=null&&num(r.optimum_pressure_mpa)!=null).slice(0,1100);plot('phys3d',[{x:a.map(r=>num(r.avg_optimum_temp_c)),y:a.map(r=>num(r.avg_optimum_ph)),z:a.map(r=>num(r.optimum_pressure_mpa)),mode:'markers',type:'scatter3d',text:a.map(r=>r.name),marker:{size:4,color:a.map(r=>num(r.avg_optimum_temp_c)),colorscale:'Turbo',opacity:.72},customdata:a.map(r=>[r.environment,r.metabolism_pathways||'—']),hovertemplate:'<b>%{text}</b><br>Topt %{x} °C · pH %{y} · pressure %{z} MPa<br>%{customdata[0]}<br>%{customdata[1]}<extra></extra>'}],{scene:{xaxis:{title:'Topt °C'},yaxis:{title:'pHopt'},zaxis:{title:'Pressure MPa'}},title:{text:'Measured physiological geometry · 3D',font:{size:13}},margin:{l:5,r:5,t:45,b:5}});
 const poly=[['0–1 extreme dimensions',D.polyextremophily['0-1_extreme_dimensions']],['2 extreme dimensions',D.polyextremophily['2_extreme_dimensions']]];plot('polyextreme',[{labels:poly.map(x=>x[0]),values:poly.map(x=>x[1]),type:'pie',hole:.58,hovertemplate:'%{label}<br>%{value} records<br>%{percent}<extra></extra>'}],{title:{text:'Polyextremophily in the release',font:{size:13}},showlegend:true});
 const envs=Object.keys(D.environment_top).slice(0,7),paths=['methanogenesis','sulfate-reduction','sulfur-reduction','iron-reduction','fermentation','hydrogen-oxidation'];const nodes=['Environment',...envs,'Pathway',...paths];const ix={};nodes.forEach((n,i)=>ix[n]=i);const src=[],tar=[],val=[];envs.forEach(en=>paths.forEach(pth=>{const v=D.records.filter(r=>r.environment===en&&hasPath(r,pth)).length;if(v){src.push(ix[en]);tar.push(ix[pth]);val.push(v)}}));plot('integratedSankey',[{type:'sankey',node:{label:nodes,pad:12,thickness:13},link:{source:src,target:tar,value:val}}],{title:{text:'Environment → metabolic pathway flows',font:{size:13}},margin:{l:5,r:5,t:40,b:5}});
 const obs=['Environment','Taxonomy','Chemistry','Physiology','Planetary constraints'];const support=[4,4,3,3,1];plot('hypothesisMap',[{type:'scatterpolar',r:support,theta:obs,fill:'toself',name:'Analytical leverage',hovertemplate:'%{theta}: %{r}/4<extra></extra>'}],{polar:{radialaxis:{range:[0,4],dtick:1}},showlegend:false,title:{text:'Which layers support which inference?',font:{size:13}}});
 const envList=Object.entries(D.environment_top).slice(0,10);const matrix=envList.map(([en])=>paths.map(pth=>D.records.filter(r=>r.environment===en&&hasPath(r,pth)).length));plot('associationHeat',[{z:matrix,x:paths,y:envList.map(x=>x[0]),type:'heatmap',colorscale:'Viridis',hovertemplate:'%{y}<br>%{x}: %{z} records<extra></extra>'}],{title:{text:'Integrated association map · environment × metabolism',font:{size:13}},margin:{l:170,r:20,t:50,b:90}});
 const feat=D.records.filter(r=>num(r.avg_optimum_temp_c)!=null&&num(r.avg_optimum_ph)!=null).slice(0,1000);plot('featureSpace',[{type:'splom',dimensions:[{label:'Topt',values:feat.map(r=>num(r.avg_optimum_temp_c))},{label:'pHopt',values:feat.map(r=>num(r.avg_optimum_ph))},{label:'Salinity',values:feat.map(r=>num(r.avg_opt_salinity_percent_normalized_v40))}],text:feat.map(r=>r.name),marker:{size:3,opacity:.5}}],{title:{text:'Pairwise physiological feature space',font:{size:13}},dragmode:'select',margin:{l:20,r:20,t:45,b:20}});
 setText('analysisDeep',cardInsight('THE INTEGRATED QUESTION','A pattern becomes scientifically useful when multiple layers agree.',`The integrated views put environmental categories beside metabolism, chemistry and physiology. This is where the project moves beyond one-variable EDA: a candidate relationship can now be followed across several independent representations.`)+cardInsight('NEXT TEST','But association can still be inherited from lineage.',`A metabolic pathway may appear predictable because the organisms carrying it belong to a recognizable clade. The next step is therefore an explicit model stress test, not a stronger descriptive chart.`));
}

function renderML(){
 const tab=currentML;
 if(tab==='random')renderMLRandom();else if(tab==='grouped')renderMLGrouped();else renderMLExtreme();
}
function renderMLRandom(){const rows=D.ml_random;plot('mlChart',[{x:rows.map(x=>x.pathway),y:rows.map(x=>x.environment),type:'bar',name:'Environment',text:rows.map(x=>x.environment.toFixed(3)),textposition:'outside',hovertemplate:'%{x}<br>Environment-only ROC-AUC %{y:.3f}<extra></extra>'},{x:rows.map(x=>x.pathway),y:rows.map(x=>x.taxonomy),type:'bar',name:'Taxonomy',hovertemplate:'%{x}<br>Taxonomy-only %{y:.3f}<extra></extra>'},{x:rows.map(x=>x.pathway),y:rows.map(x=>x.combined),type:'bar',name:'Combined',hovertemplate:'%{x}<br>Combined %{y:.3f}<extra></extra>'}],{barmode:'group',yaxis:{range:[0,1.05],title:'ROC-AUC'},xaxis:{automargin:true,tickangle:-22},title:{text:'Random 5-fold: environment vs taxonomy vs combined',font:{size:13}}});
 const first=rows.find(x=>x.pathway===activePathway)||rows[0];renderMLDetail(first);plot('mlStress',[{x:rows.map(x=>x.pathway),y:rows.map(x=>x.environment),name:'Environment',type:'bar'},{x:rows.map(x=>x.pathway),y:rows.map(x=>x.taxonomy),name:'Taxonomy',type:'bar'},{x:rows.map(x=>x.pathway),y:rows.map(x=>x.combined),name:'Combined',type:'bar'}],{barmode:'group',yaxis:{range:[0,1]},xaxis:{automargin:true,tickangle:-22},title:{text:'Random-fold performance by pathway',font:{size:13}}});setText('mlHeader',`<b>Random 5-fold is the permissive test.</b><span>It estimates predictive association when related lineages can appear in both training and test. That is useful, but it can overstate environmental generalization.</span>`);setText('mlExplain','Random folds answer “can these variables predict the pathway in this sample?” They do not by themselves answer “will this relationship transfer beyond the sampled lineages?”');setText('mlDeep',cardInsight('WHAT TO NOTICE','Combined models can be almost perfect without proving environmental causation.',`Methanogenesis reaches 1.000 ROC-AUC in the combined model, while taxonomy alone is already 0.995. That is a clue to inspect lineage structure rather than a reason to declare the environment sufficient.`));}
function renderMLGrouped(){const rows=D.ml_grouped.filter(x=>x.roc!=null);plot('mlChart',[{x:rows.map(x=>x.pathway),y:rows.map(x=>x.roc),type:'bar',text:rows.map(x=>x.roc.toFixed(3)),textposition:'outside',hovertemplate:'%{x}<br>Grouped environment-only ROC-AUC %{y:.3f}<extra></extra>'}],{yaxis:{range:[0,1]},xaxis:{automargin:true,tickangle:-22},title:{text:'Phylum-grouped environment-only validation',font:{size:13}}});const first=rows.find(x=>x.pathway===activePathway)||rows[0];if(first)renderMLDetail({pathway:first.pathway,environment:first.roc,taxonomy:null,combined:null});plot('mlStress',[{x:D.ml_grouped.map(x=>x.pathway),y:D.ml_grouped.map(x=>x.roc??0),name:'ROC-AUC',type:'bar'},{x:D.ml_grouped.map(x=>x.pathway),y:D.ml_grouped.map(x=>x.pr??0),name:'PR-AUC',type:'bar'},{x:D.ml_grouped.map(x=>x.pathway),y:D.ml_grouped.map(x=>x.balanced??0),name:'Balanced accuracy',type:'bar'}],{barmode:'group',yaxis:{range:[0,1]},xaxis:{automargin:true,tickangle:-22},title:{text:'Grouped validation: three complementary metrics',font:{size:13}}});setText('mlHeader',`<b>Lineage control changes the interpretation.</b><span>Phylum-grouped holdout asks whether an environment-only model can generalize to lineages withheld from training.</span>`);setText('mlExplain','Sulfate, sulfur and iron reduction plus fermentation retain useful environment signal. H₂ oxidation does not: its random-CV signal collapses under lineage control. Methanogenesis cannot be estimated under this split because all positives are in one phylum.');setText('mlDeep',cardInsight('NEGATIVE RESULT','H₂ oxidation is the stress test to remember.',`Environment-only ROC-AUC falls from <strong>0.815</strong> in random folds to <strong>0.213</strong> under phylum holdout. The ordinary CV result therefore should not be described as robust environmental generalization.`)+cardInsight('LIMITATION','Methanogenesis is not lineage-independent ML evidence here.',`All 52 methanogenesis positives are Euryarchaeota, so the grouped environment-only metric is not estimable. The pathway remains important for Enceladus for independent planetary and experimental reasons, not because this particular grouped classifier proves it.`));}
function renderMLExtreme(){const e=D.extreme;plot('mlChart',[{x:['ROC-AUC','PR-AUC','Balanced accuracy'],y:[e.roc_auc,e.pr_auc,e.balanced_accuracy],type:'bar',text:[e.roc_auc,e.pr_auc,e.balanced_accuracy].map(x=>x.toFixed(3)),textposition:'outside',hovertemplate:'%{x}: %{y:.3f}<extra></extra>'}],{yaxis:{range:[0,1]},title:{text:'Extreme thermal niche classifier · Topt ≥ 80°C',font:{size:13}}});plot('mlStress',[{x:['All records','≥80°C positives'],y:[e.n,e.positive],type:'bar',hovertemplate:'%{x}: %{y}<extra></extra>'}],{title:{text:'Class balance for the extreme-niche target',font:{size:13}},yaxis:{title:'Records'}});setText('mlHeader',`<b>A separate classification question.</b><span>Can environmental/ecological characteristics identify organisms occupying extreme thermal niches?</span>`);setText('mlExplain',`The classifier uses ${e.n.toLocaleString()} records with ${e.positive} positives at Topt ≥80°C. ROC-AUC is ${fmt(e.roc_auc,3)}, PR-AUC ${fmt(e.pr_auc,3)}, balanced accuracy ${fmt(e.balanced_accuracy,3)}.`);setText('mlMetricDetail',`<div class="big-score">${fmt(e.roc_auc,3)}</div><span>ROC-AUC</span><dl><dt>Target</dt><dd>${esc(e.target)}</dd><dt>Records</dt><dd>${e.n}</dd><dt>Positive</dt><dd>${e.positive}</dd><dt>PR-AUC</dt><dd>${fmt(e.pr_auc,3)}</dd><dt>Balanced accuracy</dt><dd>${fmt(e.balanced_accuracy,3)}</dd></dl>`);setText('mlDeep',cardInsight('WHY IT MATTERS','Extreme thermal adaptation is predictable enough to be scientifically useful — but not a proxy for habitability.',`The model addresses a narrower physiological question. It should be read alongside the metabolic models, not as a single “extremophile score.”`));}
function renderMLDetail(x){const detail=$('#mlMetricDetail');if(!detail)return;detail.innerHTML=`<div class="pathway-select">${esc(x.pathway)}</div><dl><dt>Environment-only ROC-AUC</dt><dd>${fmt(x.environment,3)}</dd><dt>Taxonomy-only ROC-AUC</dt><dd>${fmt(x.taxonomy,3)}</dd><dt>Combined ROC-AUC</dt><dd>${fmt(x.combined,3)}</dd><dt>Interpretation</dt><dd>${esc(x.note||'Compare with grouped validation')}</dd></dl>`;const rr=D.ml_grouped.find(g=>g.pathway.toLowerCase()===String(x.pathway).toLowerCase());if(rr&&rr.roc!=null)plot('mlPrChart',[{x:['ROC-AUC','PR-AUC','Balanced accuracy'],y:[rr.roc,rr.pr,rr.balanced],type:'bar',hovertemplate:'%{x}: %{y:.3f}<extra></extra>'}],{yaxis:{range:[0,1]},title:{text:`${x.pathway} · grouped metrics`,font:{size:12}}});else plot('mlPrChart',[{x:['Environment','Taxonomy','Combined'],y:[x.environment??0,x.taxonomy??0,x.combined??0],type:'bar'}],{yaxis:{range:[0,1]},title:{text:`${x.pathway} · random-fold comparison`,font:{size:12}}})}

function renderSynthesis(){
 const chain=[['Environment',4],['Physiology',4],['Metabolism',4],['Chemistry',3],['Biosignature',2],['Planetary inference',1]];plot('synthesisChain',[{x:chain.map(x=>x[0]),y:chain.map(x=>x[1]),type:'scatter',mode:'lines+markers',line:{shape:'spline',width:3},marker:{size:11},hovertemplate:'%{x}<br>relative evidentiary leverage %{y}/4<extra></extra>'}],{yaxis:{range:[0,4.4],dtick:1,title:'Evidence / analytical leverage'},title:{text:'The reasoning chain becomes weaker as assumptions accumulate',font:{size:13}}});
 const robust=[['Thermal envelopes',4],['Environment associations',3],['Grouped ML for several pathways',3],['H₂ oxidation generalization',1],['Methanogenesis as lineage-independent ML',0],['Enceladus life detection',1]];plot('robustnessMap',[{x:robust.map(x=>x[0]),y:robust.map(x=>x[1]),type:'bar',text:robust.map(x=>['strong','moderate','moderate','weak','not estimable','hypothesis'][robust.indexOf(x)]),textposition:'outside',hovertemplate:'%{x}<br>support level %{y}/4<extra></extra>'}],{yaxis:{range:[0,4.5],dtick:1,title:'Support level'},xaxis:{automargin:true,tickangle:-25},title:{text:'Where ThermoBase currently has leverage — and where it does not',font:{size:13}}});
 setText('openQuestions',[['Can richer chemical-role provenance reduce the 170 unresolved records?','Chemistry'],['Can exact genome/sequence mapping support a ThermoBase-specific phylogenetic analysis?','Phylogeny'],['Which environmental relationships persist under stricter lineage or leave-one-environment-out validation?','ML'],['What measurements would most reduce Enceladus abiotic ambiguity?','Planetary science'],['Can future mission observations be mapped directly onto ThermoBase-compatible metabolic constraints?','Astrobiology']].map(x=>`<div><span>${esc(x[1])}</span><b>${esc(x[0])}</b></div>`).join(''));
}
function worldData(){return{
 enceladus:{title:'Enceladus',kind:'Ocean world · plume-accessible',stance:'Strongest ThermoBase case study — rich access to ocean-derived material does not equal evidence of life.',score:'14/14',scoreLabel:'ordinal compatibility of the hydrogenotrophic pathway',evidence:['Cassini established a global subsurface ocean and sampled its plume','Molecular H₂ is consistent with hydrothermal water–rock chemistry','CH₄, CO₂ and other plume constituents provide a redox/chemical context','Phosphate has been detected in plume material','2025 work found diverse organics in fresh plume ice grains; 2026 work stresses the abiotic baseline'],thermo:'ThermoBase identifies hydrogenotrophic methanogenesis as the leading metabolic hypothesis in the 14-criterion matrix. This is a compatibility result, not a life probability. No single terrestrial organism matches every inferred Enceladus constraint.',sources:D.web_release.planetary_sources.Enceladus},
 europa:{title:'Europa',kind:'Ocean world · in situ mission target',stance:'High habitability interest, but many of the environmental variables needed for a ThermoBase-style pathway score remain incompletely constrained.',score:'Not scored',scoreLabel:'same 14-criterion score not justified',evidence:['Strong evidence for a global salty subsurface ocean','Europa Clipper is en route; NASA lists arrival at Jupiter in 2030','2026 re-analysis identified ammonia-bearing compounds on the surface','Surface fractures may provide routes for ocean-derived material','No persistent plume sampling comparable to Enceladus has been established'],thermo:'ThermoBase is useful here as an analogue library: it can identify terrestrial redox metabolisms compatible with candidate temperature, pH and electron-donor/acceptor regimes, but should not invent missing Europa constraints.',sources:D.web_release.planetary_sources.Europa},
 trappist:{title:'TRAPPIST-1 e',kind:'Earth-size habitable-zone exoplanet · remote sensing',stance:'A remote atmospheric target whose current value lies in constraining whether an atmosphere exists, not in assigning a life score.',score:'Not scored',scoreLabel:'atmospheric state remains under study',evidence:['Earth-sized planet in the habitable zone of an active red dwarf','NASA reports Webb observations of planet e remain under study','Thick hydrogen-rich atmospheres are ruled out by current data','Stellar activity complicates separation of planetary and stellar signals','Further transit observations are required'],thermo:'ThermoBase contributes a framework for linking candidate environments to terrestrial metabolic niches. It cannot turn a remote transmission spectrum into an organism-level prediction.',sources:D.web_release.planetary_sources['TRAPPIST-1 e']},
 k218:{title:'K2-18 b',kind:'Sub-Neptune · atmospheric chemistry',stance:'Interesting molecular inventory, but atmospheric molecules are not equivalent to biological evidence.',score:'Not scored',scoreLabel:'no ThermoBase life probability assigned',evidence:['JWST observations report methane and carbon dioxide','NASA notes the atmospheric interpretation remains an active area of study','The possible DMS detection is less robust and requires validation','Planetary structure differs strongly from terrestrial extremophile habitats','Any biosignature claim requires an abiotic baseline'],thermo:'The scientifically useful comparison is process-based: which terrestrial metabolisms can produce a molecule, what environmental constraints do they require, and what abiotic processes can produce the same molecule?',sources:D.web_release.planetary_sources['K2-18 b']},
 earth:{title:'Earth benchmark',kind:'Known biosphere · control case',stance:'The reference world: life is independently established, so metabolism and environmental occupation can be studied directly.',score:'Reference',scoreLabel:'known life; not a probability score',evidence:['Life occupies enormous thermal, chemical and ecological diversity','ThermoBase is grounded in terrestrial extremophile observations','Metabolic transformations can be directly observed and experimentally tested','Earth provides the calibration domain for biosignature reasoning'],thermo:'Earth is the control against which the entire ThermoBase reasoning chain is calibrated. It is not an “Earth-like planet score.”',sources:[]}
}}
function renderWorld(w){currentWorld=w;const x=worldData()[w];setText('worldContent',`<div class="world-card"><div><span class="tag">${esc(x.kind)}</span><h3>${esc(x.title)}</h3><p>${esc(x.stance)}</p><div class="world-evidence">${x.evidence.map((e,i)=>`<div><b>${i<2?'OBSERVED / CONSTRAINED':i===2?'CURRENT INTERPRETATION':'OPEN QUESTION'}</b>${esc(e)}</div>`).join('')}</div></div><div><div class="world-score">${esc(x.score)}<small>${esc(x.scoreLabel)}</small></div><div class="world-callout"><b>ThermoBase contribution</b><p>${esc(x.thermo)}</p></div></div></div>`);setText('worldSources',x.sources.length?`<b>Current sources</b>${x.sources.map(s=>`<a href="${esc(s.url)}" target="_blank" rel="noopener">${esc(s.label)} ↗</a>`).join('')}`:'<b>Benchmark</b><span>Earth is the known-life control; no planetary compatibility score is applied.</span>');
 const p=D.pathways;plot('pathwayCompare',[{x:p.map(x=>x.score),y:p.map(x=>x.pathway),type:'bar',orientation:'h',text:p.map(x=>x.interpretation),hovertemplate:'%{y}<br>Compatibility %{x}/14<br>%{text}<extra></extra>'}],{xaxis:{title:'Ordinal compatibility score / 14',range:[0,14]},margin:{l:225,r:25,t:35,b:45},title:{text:'Enceladus pathway discrimination · compatibility, not probability',font:{size:13}}});
 const evidence={enceladus:[5,4,3,2,1],europa:[4,4,3,2,1],trappist:[2,3,3,2,1],k218:[3,3,3,2,1],earth:[5,5,5,1,0]}[w];plot('worldEvidenceLadder',[{x:['Direct observation','Strong constraint','Inference','Hypothesis','Unknown'],y:evidence,type:'bar',hovertemplate:'%{x}<br>relative evidence level %{y}<extra></extra>'}],{yaxis:{range:[0,5]},title:{text:`Evidence maturity · ${x.title}`,font:{size:13}}});
 const nodes=['H₂','CO₂','CH₄','H₂O','hydrothermal chemistry','methanogens','abiotic methane'];plot('enceladusNetwork',[{type:'sankey',node:{label:nodes,pad:22,thickness:18},link:{source:[0,1,4,5,6],target:[2,2,0,2,2],value:[8,7,5,6,6]}}],{title:{text:'Conceptual redox logic for the Enceladus case',font:{size:13}},margin:{l:5,r:5,t:42,b:5}});plot('abioticRadar',[{type:'scatterpolar',r:[3,3,2,3,2,3],theta:['Internal temperature','Rheology','Lithology','Abiotic organics','Ocean transport','Isotopic baseline'],fill:'toself',name:'Uncertainty to reduce'}],{polar:{radialaxis:{range:[0,3],tickvals:[1,2,3],ticktext:['lower','medium','high']}},showlegend:false,title:{text:'What the 2026 framework says must be constrained',font:{size:13}}});
 const worldRows=[['Enceladus','Plume-accessible',1],['Europa','Ocean world',0],['TRAPPIST-1 e','Remote exoplanet',0],['K2-18 b','Atmospheric target',0],['Earth','Known biosphere',2]];plot('worldComparison',[{x:worldRows.map(x=>x[0]),y:worldRows.map(x=>x[2]),type:'bar',customdata:worldRows.map(x=>x[1]),hovertemplate:'%{x}<br>Framework state: %{y}<br>%{customdata}<extra></extra>'}],{yaxis:{tickvals:[0,1,2],ticktext:['Not scored','Case study','Known-life control'],range:[0,2.3]},title:{text:'Why the worlds are not assigned a common life score',font:{size:13}}});
 $$('[data-world]').forEach(b=>b.classList.toggle('active',b.dataset.world===w));
}

function showRecord(id){const r=D.records.find(x=>String(x.record_id)===String(id));if(!r)return;openChat();addChat('assistant',`<strong>${esc(r.name)}</strong><br><span class="reaction">Record ${esc(r.record_id)}</span><br>Domain: ${esc(r.domain||'—')} · Phylum: ${esc(r.phylum||'—')}<br>Environment: ${esc(r.environment||'—')}<br>Tmin/Topt/Tmax: ${r.min_temp_c??'—'} / ${r.avg_optimum_temp_c??'—'} / ${r.max_temp_c??'—'} °C<br>pHopt: ${r.avg_optimum_ph??'—'} · Pressure: ${r.optimum_pressure_mpa??'—'} MPa<br>Pathways: ${esc(r.metabolism_pathways||'—')}<br>Compounds: ${esc(r.extracted_compounds||'—')}<br>QC: ${esc(r.final_qc_record_status_v71||'—')}`)}
function updateChatContext(){const active=$('.nav.active');const n=filtered().length;setText('chatContext',`Current context: ${active?.textContent?.replace(/^\s*\d+\s*/,'').trim()||'Overview'} · ${n.toLocaleString()} filtered records`)}
function openChat(){const c=$('#researchChat');if(!c)return;c.classList.add('open');c.setAttribute('aria-hidden','false');$('#chatFab').style.display='none';updateChatContext();setTimeout(()=>$('#chatQuestion')?.focus(),40)}
function closeChat(){const c=$('#researchChat');if(!c)return;c.classList.remove('open');c.setAttribute('aria-hidden','true');$('#chatFab').style.display=''}
function addChat(role,text){const body=$('#chatBody');if(!body)return;const d=document.createElement('div');d.className='chat-msg '+role;d.innerHTML=`<b>${role==='user'?'You':'ThermoBase'}</b><p>${text}</p>`;body.appendChild(d);body.scrollTop=body.scrollHeight}
function chatVisual(kind='physiology'){const a=filtered().filter(r=>num(r.avg_optimum_temp_c)!=null&&num(r.avg_optimum_ph)!=null);const box=$('#chatVisual');if(!box)return;box.classList.add('active');box.innerHTML='<div id="chatPlot" class="plot"></div>';plot('chatPlot',[{x:a.map(r=>num(r.avg_optimum_temp_c)),y:a.map(r=>num(r.avg_optimum_ph)),mode:'markers',type:'scattergl',text:a.map(r=>r.name),customdata:a.map(r=>r.record_id),hovertemplate:'<b>%{text}</b><br>Topt %{x} °C<br>pHopt %{y}<extra></extra>'}],{xaxis:{title:'Topt (°C)'},yaxis:{title:'pHopt'},title:{text:`Filtered physiological space · ${a.length} records`,font:{size:12}}})}
function chatAnswer(q){const l=q.toLowerCase(),a=filtered(),total=a.length;
 if(/complete.*thermal|thermal.*complete|tmin|topt.*missing/.test(l))return `<strong>${D.completeness.thermal_complete.toLocaleString()}</strong> records have complete Tmin/Topt/Tmax envelopes. Missing values: Tmin ${D.missing_counts.min_temp_c}, Topt ${D.missing_counts.avg_optimum_temp_c}, Tmax ${D.missing_counts.max_temp_c}. There are 0 thermal envelope ordering violations. <small>Source: ThermoBase QC layer.</small>`;
 if(/complete.*p[hH]|p[hH].*missing|p[hH].*coverage/.test(l))return `<strong>${D.completeness.ph_complete.toLocaleString()}</strong> records have complete pHmin/pHopt/pHmax envelopes. Missing: pHmin ${D.missing_counts.min_ph}, pHopt ${D.missing_counts.avg_optimum_ph}, pHmax ${D.missing_counts.max_ph}. There are 0 complete-envelope ordering violations. <small>Source: ThermoBase QC layer.</small>`;
 if(/337|fields|columns|schema|architecture/.test(l))return `ThermoBase has <strong>337 structured fields</strong>. The schema is partitioned into ${Object.entries(D.schema_groups).map(([k,v])=>`<b>${esc(k)}</b> (${v})`).join(', ')}. Use Evidence & quality → 337-field architecture to browse the actual release schema.`;
 if(/hydrogen oxidation|h2 oxidation/.test(l)&&/lineage|grouped|stress|model|predict/.test(l))return `H₂ oxidation falls from random-fold environment-only ROC-AUC <strong>0.815</strong> to phylum-grouped <strong>0.213</strong>. The apparent random-CV environmental signal therefore does not survive lineage control. <small>Source: final lineage-controlled ML.</small>`;
 if(/methanogenesis/.test(l)&&/ml|predict|model|lineage|grouped/.test(l))return `Methanogenesis has random environment-only ROC-AUC <strong>0.953</strong>; combined reaches 1.000. But grouped validation is <strong>not estimable</strong> because all 52 positives are Euryarchaeota. That is not lineage-independent environmental evidence.`;
 if(/lineage|grouped|stress/.test(l))return `Phylum-grouped environment-only ROC-AUC: sulfate reduction <strong>0.838</strong>, sulfur reduction <strong>0.835</strong>, iron reduction <strong>0.852</strong>, fermentation <strong>0.858</strong>, H₂ oxidation <strong>0.213</strong>. Methanogenesis is not estimable under this split.`;
 if(/extreme|80.*c|80°|high temperature/.test(l)&&/model|classifier|ml|predict/.test(l))return `The Topt ≥80°C classifier uses <strong>${D.extreme.n.toLocaleString()}</strong> records with <strong>${D.extreme.positive}</strong> positives: ROC-AUC ${fmt(D.extreme.roc_auc,3)}, PR-AUC ${fmt(D.extreme.pr_auc,3)}, balanced accuracy ${fmt(D.extreme.balanced_accuracy,3)}.`;
 if(/14.?\/ ?14|probability.*life|chance.*life|enceladus.*score/.test(l))return `The Enceladus matrix gives hydrogenotrophic methanogenesis <strong>14/14</strong>. This is an <strong>ordinal compatibility score across 14 criteria</strong>, not a probability of life. The 2026 abiotic-baseline framework emphasizes that CH₄ isotope or chirality signals remain ambiguous unless internal temperature, rheology, lithology, abiotic organic inventory and ocean transport are constrained.`;
 if(/search|find/.test(l)){const term=l.match(/methane|hydrogen|h2|sulfate|sulfur|iron|co2|carbon dioxide|acetate|nitrate/);if(term){const t=term[0];const hits=D.records.filter(r=>[r.name,r.metabolism_pathways,r.extracted_compounds,r.predicted_biosignature_species,r.environment].some(v=>String(v||'').toLowerCase().includes(t))).slice(0,10);return `<strong>${hits.length}</strong> matching records for <b>${esc(t)}</b>: ${hits.map(r=>`<br>• ${esc(r.name)} — ${esc(r.environment||'—')} — ${esc(r.metabolism_pathways||'—')}`).join('')||'<br>No matching record in the release.'}`}}
 if(/chemical|compound|donor|acceptor|product|role/.test(l))return `The chemistry layer contains <strong>800</strong> records with no extracted compounds, <strong>264</strong> closed high-confidence records, <strong>109</strong> partial high-confidence records with unresolved remainder, and <strong>65</strong> unresolved-context records. The rule is explicit: compound mention ≠ automatically assigned metabolic role.`;
 if(/how many|number of|records|organisms|dataset/.test(l))return `The full release contains <strong>${D.meta.records.toLocaleString()} organisms</strong> and <strong>${D.meta.columns} structured fields</strong>. The current filter context contains <strong>${total.toLocaleString()}</strong> records.`;
 if(/median.*temperature|topt/.test(l))return `Median available Topt in the current filter is <strong>${fmt(median(vals(a,'avg_optimum_temp_c')),1)} °C</strong>.`;
 if(/median.*p[hH]|optimum p[hH]/.test(l))return `Median available pHopt in the current filter is <strong>${fmt(median(vals(a,'avg_optimum_ph')),1)}</strong>.`;
 if(/show|plot|graph|visual|chart/.test(l))return `I can generate a temperature × pH plot from the current filter. Add “temperature and pH” to the question and I will render it below.`;
 return `I could not support that question from the local ThermoBase research layer. Try asking about <b>thermal QC</b>, <b>pH coverage</b>, <b>337 fields</b>, <b>chemistry roles</b>, <b>lineage-controlled ML</b>, a compound/pathway search, or the <b>Enceladus 14/14 score</b>.`}
function submitChat(q){q=q.trim();if(!q)return;addChat('user',esc(q));addChat('assistant',chatAnswer(q));const l=q.toLowerCase();if(/show|plot|graph|visual|chart/.test(l)&&/temperature|temp|p[hH]|physiolog/.test(l))chatVisual()}

function bind(){
 $$('.nav').forEach(b=>b.onclick=()=>go(b.dataset.view));$$('[data-jump]').forEach(b=>b.onclick=()=>go(b.dataset.jump));
 ['fDomain','fEnvironment','fTopt','fPh','fMet'].forEach(id=>$('#'+id)?.addEventListener('input',()=>{renderPhys();updateChatContext()}));
 $('#resetFilters')?.addEventListener('click',()=>{['fDomain','fEnvironment','fTopt','fPh','fMet'].forEach(id=>{if($('#'+id))$('#'+id).value=''});go('physiology')});$('#themeToggle')?.addEventListener('click',toggleTheme);
 $('#metSearch')?.addEventListener('input',e=>renderMetSearch(e.target.value));$('#clearMet')?.addEventListener('click',()=>{$('#metSearch').value='';renderMetSearch('')});
 $('#schemaSearch')?.addEventListener('input',renderSchema);$('#schemaGroup')?.addEventListener('change',renderSchema);
 $('#chatFab')?.addEventListener('click',openChat);$('#chatClose')?.addEventListener('click',closeChat);$('#chatForm')?.addEventListener('submit',e=>{e.preventDefault();const q=$('#chatQuestion');submitChat(q.value);q.value=''});
 $$('#mlTabs [data-ml]').forEach(b=>b.onclick=()=>{currentML=b.dataset.ml;$$('#mlTabs [data-ml]').forEach(x=>x.classList.toggle('active',x.dataset.ml===currentML));renderML()});
 document.addEventListener('click',e=>{const rec=e.target.closest('[data-record]');if(rec)showRecord(rec.dataset.record);const w=e.target.closest('[data-world]');if(w)renderWorld(w.dataset.world);const q=e.target.closest('[data-chatq]');if(q){openChat();submitChat(q.dataset.chatq)}const ep=e.target.closest('[data-envpath]');if(ep&&activeEnv)drillEnvironment(activeEnv,ep.dataset.envpath);const nav=e.target.closest('[data-jump]');if(nav)go(nav.dataset.jump)});
 window.addEventListener('scroll',()=>{const den=document.body.scrollHeight-innerHeight;$('#progress').style.width=(den>0?scrollY/den*100:0)+'%'});
}
document.addEventListener('keydown',e=>{if(e.target===$('#chatQuestion')&&e.key==='Enter'&&!e.shiftKey){e.preventDefault();$('#chatForm')?.requestSubmit()}if(e.key==='Escape'&&$('#researchChat')?.classList.contains('open'))closeChat()});
window.addEventListener('resize',()=>document.querySelectorAll('.js-plotly-plot').forEach(el=>{try{Plotly.Plots.resize(el)}catch{}}));
fetch('data/thermobase.json').then(r=>{if(!r.ok)throw new Error('data fetch failed');return r.json()}).then(d=>{D=d;init()}).catch(e=>{console.error(e);if($('#dataStatus'))$('#dataStatus').textContent='research layer unavailable — check data/thermobase.json'});
