const $=s=>document.querySelector(s);let organisms=[],filtered=[],shown=60;
const plotCfg={responsive:true,displaylogo:false,modeBarButtonsToRemove:['lasso2d','select2d']};
const layoutBase={paper_bgcolor:'transparent',plot_bgcolor:'transparent',font:{family:'DM Sans, sans-serif',color:'#101314',size:11},margin:{l:55,r:20,t:25,b:50},hoverlabel:{font:{family:'DM Sans, sans-serif'}}};
async function load(){const [o,metrics,ml,grp,ext,path]=await Promise.all(['organisms.json','metrics.json','ml_random.json','ml_grouped.json','ml_extreme.json','enceladus_pathways.json'].map(x=>fetch('data/'+x).then(r=>r.json())));organisms=o;filtered=o;renderDomain(metrics);renderThermal(o);renderSpace();renderML(ml);renderGrouped(grp);renderExtreme(ext);renderPath(path);initExplorer();}
function renderDomain(m){Plotly.newPlot('domainChart',[{type:'bar',x:Object.keys(m.domain_counts),y:Object.values(m.domain_counts),text:Object.values(m.domain_counts),textposition:'outside',hovertemplate:'%{x}<br>%{y} organisms<extra></extra>'}],{...layoutBase,title:{text:'Who is represented?',font:{size:15}},yaxis:{title:'Organisms',gridcolor:'#e5e3dc'},xaxis:{title:''},height:300},plotCfg)}
function vals(col){return organisms.map(o=>Number(o[col])).filter(Number.isFinite)}
function renderThermal(){Plotly.newPlot('thermalChart',[{type:'box',y:vals('min_temp_c'),name:'Tmin',boxpoints:false},{type:'box',y:vals('avg_optimum_temp_c'),name:'Topt',boxpoints:false},{type:'box',y:vals('max_temp_c'),name:'Tmax',boxpoints:false}],{...layoutBase,showlegend:true,yaxis:{title:'Temperature (°C)',gridcolor:'#e5e3dc'},margin:{l:55,r:20,t:25,b:45}},plotCfg)}
function renderSpace(){const dom=$('#domainFilter').value,maxT=+$('#tempSlider').value,mode=$('#pointMode').value;const a=organisms.filter(o=>(dom==='all'||o.domain===dom)&&Number(o.avg_optimum_temp_c)<=maxT&&(mode==='all'||(mode==='thermal'&&o.avg_optimum_temp_c!=null&&o.min_temp_c!=null&&o.max_temp_c!=null)||(mode==='complete'&&o.avg_optimum_temp_c!=null&&o.min_temp_c!=null&&o.max_temp_c!=null&&o.avg_optimum_ph!=null&&o.min_ph!=null&&o.max_ph!=null))).filter(o=>Number.isFinite(+o.avg_optimum_temp_c)&&Number.isFinite(+o.avg_optimum_ph));const domains=['Bacteria','Archaea','Eukaryota'];const traces=domains.map(d=>{const z=a.filter(o=>o.domain===d);return {type:'scatter',mode:'markers',name:d,x:z.map(o=>+o.avg_optimum_temp_c),y:z.map(o=>+o.avg_optimum_ph),text:z.map(o=>o.name),customdata:z.map(o=>[o.record_id,o.environment,o.phylum,o.ecosystem]),marker:{size:z.map(o=>Math.max(5,Math.min(18,(+o.max_temp_c||+o.avg_optimum_temp_c)-(+o.min_temp_c||+o.avg_optimum_temp_c)+2))),opacity:.7},hovertemplate:'<b>%{text}</b><br>Topt %{x:.1f}°C<br>pHopt %{y:.1f}<br>%{customdata[1]}<extra></extra>'}});Plotly.react('spaceChart',traces,{...layoutBase,legend:{orientation:'h',y:1.08},xaxis:{title:'Optimum growth temperature (°C)',gridcolor:'#e5e3dc'},yaxis:{title:'Optimum pH',gridcolor:'#e5e3dc'},margin:{l:60,r:20,t:25,b:55}},plotCfg)}
function renderML(data){const paths=[...new Set(data.map(x=>x.pathway))],sets=[...new Set(data.map(x=>x.predictor_set))];const colors={};const traces=sets.map((s,i)=>({type:'bar',name:s.replaceAll('_',' '),x:paths,y:paths.map(p=>{const r=data.find(x=>x.pathway===p&&x.predictor_set===s);return r?.ROC_AUC??null}),hovertemplate:'%{x}<br>ROC-AUC %{y:.3f}<extra></extra>'}));Plotly.newPlot('mlChart',traces,{...layoutBase,barmode:'group',legend:{orientation:'h'},yaxis:{title:'ROC-AUC',range:[0,1.05],gridcolor:'#e5e3dc'},xaxis:{tickangle:-25},margin:{l:55,r:20,t:25,b:95}},plotCfg)}
function renderGrouped(data){const x=data.map(r=>r.pathway),y=data.map(r=>r.grouped_ROC_AUC);Plotly.newPlot('groupedChart',[{type:'bar',x,y,text:y.map(v=>v==null?'not estimable':v.toFixed(3)),textposition:'outside',hovertemplate:'%{x}<br>%{text}<extra></extra>'}],{...layoutBase,yaxis:{title:'Phylum-grouped ROC-AUC',range:[0,1.05],gridcolor:'#e5e3dc'},xaxis:{tickangle:-25},margin:{l:60,r:20,t:25,b:95}},plotCfg)}
function renderExtreme(){Plotly.newPlot('extremeChart',[{type:'bar',x:['ROC-AUC','PR-AUC','Balanced accuracy'],y:[.936679,.613893,.872812],hovertemplate:'%{x}: %{y:.3f}<extra></extra>'}],{...layoutBase,yaxis:{range:[0,1],gridcolor:'#e5e3dc'},margin:{l:45,r:10,t:10,b:45}},plotCfg)}
function renderPath(data){const ordered=[...data].sort((a,b)=>b.compatibility_score_0_14-a.compatibility_score_0_14);Plotly.newPlot('pathwayChart',[{type:'bar',orientation:'h',y:ordered.map(x=>x.pathway),x:ordered.map(x=>x.compatibility_score_0_14),text:ordered.map(x=>x.compatibility_score_0_14+'/14'),textposition:'outside',hovertemplate:'<b>%{y}</b><br>Compatibility: %{x}/14<extra></extra>'}],{...layoutBase,xaxis:{title:'Ordinal compatibility score',range:[0,15],gridcolor:'#e5e3dc'},yaxis:{automargin:true},margin:{l:170,r:40,t:25,b:55}},plotCfg);$('#pathwayCards').innerHTML=ordered.map(x=>`<article class="pathway-card"><b>${x.compatibility_score_0_14}/14</b><h4>${x.pathway}</h4><p>${x.diagnostic_value||'See full evidence in the case study.'}</p></article>`).join('')}
function initExplorer(){const ecosystems=[...new Set(organisms.map(o=>o.ecosystem).filter(Boolean))].sort();$('#ecosystemFilter').innerHTML='<option value="all">All ecosystems</option>'+ecosystems.map(e=>`<option>${escapeHtml(e)}</option>`).join('');['organismSearch','ecosystemFilter','orgDomainFilter'].forEach(id=>$(('#'+id)).addEventListener('input',filter));$('#loadMore').onclick=()=>{shown+=60;renderTable()};renderTable()}
function filter(){const q=$('#organismSearch').value.toLowerCase().trim(),eco=$('#ecosystemFilter').value,dom=$('#orgDomainFilter').value;filtered=organisms.filter(o=>(!q||[o.name,o.phylum,o.environment,o.ecosystem,o.metabolism_pathways].filter(Boolean).join(' ').toLowerCase().includes(q))&&(eco==='all'||o.ecosystem===eco)&&(dom==='all'||o.domain===dom));shown=60;renderTable()}
function renderTable(){const rows=filtered.slice(0,shown);$('#organismRows').innerHTML=rows.map(o=>`<tr title="Record ${o.record_id}"><td><strong>${escapeHtml(o.name||'Unnamed')}</strong><br><small>${escapeHtml(o.phylum||'')}</small></td><td>${escapeHtml(o.domain||'')}</td><td>${escapeHtml(o.environment||o.ecosystem||'')}</td><td>${fmt(o.avg_optimum_temp_c,'°C')}</td><td>${fmt(o.avg_optimum_ph)}</td><td>${escapeHtml(o.metabolism_pathways||'—')}</td></tr>`).join('');$('#resultCount').textContent=`Showing ${rows.length} of ${filtered.length} matching records`;$('#loadMore').style.display=rows.length<filtered.length?'inline-block':'none'}
function fmt(v,s=''){return v==null||v===''?'—':Number.isFinite(+v)?(+v).toFixed(1)+s:v}function escapeHtml(x){return String(x??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
$('#domainFilter').addEventListener('input',renderSpace);$('#tempSlider').addEventListener('input',()=>{$('#tempValue').textContent='≤'+$('#tempSlider').value+'°C';renderSpace()});$('#pointMode').addEventListener('input',renderSpace);load().catch(e=>{console.error(e);document.body.insertAdjacentHTML('afterbegin','<div style="padding:20px;background:#fee">Could not load ThermoBase data. Run this site through a web server (e.g. GitHub Pages), not file://.</div>')});
